### ISSUE TITLE
NumberFormatException in StartsTalks.activate()

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#1074]
I see this in logs, in production:

```
[ERROR] b552866 com.rultor.Routine: #run(): java.lang.NumberFormatException: For input string: "f0120a10196294b124104354c7657562a3d4eab9" 
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) 
at java.lang.Integer.parseInt(Integer.java:492) at java.lang.Integer.parseInt(Integer.java:527) 
at com.rultor.agents.github.StartsTalks.activate(StartsTalks.java:135) 
at com.rultor.agents.github.StartsTalks.execute(StartsTalks.java:108) 
at com.rultor.spi.SuperAgent$Iterative.execute(SuperAgent.java:76) 
at com.rultor.Routine.process(Routine.java:159) 
at com.rultor.Routine.safe_aroundBody0(Routine.java:145) 
at com.rultor.Routine$AjcClosure1.run(Routine.java:1) 
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) 
at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterr upter.java:115) 
at com.rultor.Routine....
```

Doesn't look to me.. Let's find the problem and fix.

**Comment by alex-palevsky** [comment]
@yegor256 I just added bug tag here

**Comment by original-brownbear** [comment]
@yegor256 looks to me this could be the result of someone mentioning Rultor, when commenting on a commit. That would make the last part of the url ( string after last `/` is what Rultor is looking for here ) some sha hash like we see here.

You don't by any chance know what project this was in do you ? ( then we could just check and have a much simpler time reproducing/(gauging the impact of) this :) )

**Comment by alex-palevsky** [comment]
@yegor256 I added milestone `2.0` to this issue, let me know if there has to be something else

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-03fc89d9

**Comment by yegor256** [comment]
@original-brownbear no, I don't have that information (project name). but I think you're right, someone is talking to rultor in commit comments. we should deal with it correctly, I guess :)

**Comment by yegor256** [comment]
@original-brownbear and the fact that I don't have that information is a bug by itself, I think. would be much more convenient to catch all that exceptions and re-wrap them with more information about the context

**Comment by original-brownbear** [comment]
@yegor256 agreed on the exception context ticket added for that :)

As for comments, how about we simply make Rultor respond this here:
`I only work on pull requests and issues. I provide no functionality related to individual commit discussions.`

Makes sense ?

**Comment by yegor256** [comment]
@original-brownbear yep, that would be good

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed.

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear right, I added "postponed" label

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed.

@original-brownbear someone else will help in this task, no problem at all

**Comment by pnatashap** [comment]
The problem is still in place, if the comment will be for commit (as an example), exception will be thrown 
https://github.com/yegor256/rultor/blob/b0f57f31cffe8ec043641baef27bc87190344c78/src/main/java/com/rultor/agents/github/StartsTalks.java#L95-L100

**Comment by yegor256** [comment]
@pnatashap I agree, let's restrict it

**Comment by pnatashap** [comment]
@yegor256 I think that it is good to write in documentation that Rultor can work only from GitHub pull request and issue comments. (And this is how it works now: Answer can be sent only to Issue, but id has Integer type). 
In the code it is possible to improve StartTalk.execute function and to call activate only in case of issue id can be parsed for issue - '.*/issues/\d+' 
for pull - '.*/pull/\d+[/.*]'   (comments from file review have an additional part, but the answer will be posted in PR)
Other comment's will be ignored. The puzzle can be created for this, but it should be solved in jcabi-github first.

**Comment by yegor256** [comment]
@pnatashap I agree, let's do this

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1896](https://github.com/yegor256/rultor/issues/1896) is still not solved.
