### ISSUE TITLE
email notifications on release

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#748]
Let's make it possible to receive email notifications on every release, for example (`.rultor.yml`):

```
release:
  email:
    - yegor@teamed.io
    - jeff@example.com
```

Similar to what we do in `CommentsTag` we should do here - send an email to all listed addresses. The body of the email should contain similar text to what we create for the tag comment. Let's use jcabi-email for email sending.

**Comment by alex-palevsky** [comment]
this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@alevohin it's your task now

**Comment by alex-palevsky** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-64c09436`

**Comment by alevohin** [comment]
@yegor256 what subject of letter must be?

**Comment by yegor256** [comment]
@alevohin how about `${tag} released!`

**Comment by alevohin** [comment]
@yegor256 ok. Maybe something like `user/repo ${tag} released!`?
I think tag is not enough verbose (it's something like "1.3.4").

**Comment by yegor256** [comment]
@alevohin yes, totally agree

**Comment by alevohin** [comment]
@yegor256 PR was merged. Please check and close issue.

**Comment by yegor256** [comment]
@alevohin thanks!

**Comment by alex-palevsky** [comment]
@alevohin I just added **30 mins** to your account, many thanks for your contribution... +30 added to your rating, at the moment it is: [+345](http://www.netbout.com/b/35105?open=rating)

**Comment by alex-palevsky** [comment]
3 puzzles were created here: `748-9cbe7474`, `748-bb1cb5c5`, `748-a3bd319f`

**Comment by alex-palevsky** [comment]
@yegor256 last 3 puzzles `748-9cbe7474`/#830, `748-bb1cb5c5`/#828, `748-a3bd319f`/#829 that originated from here were solved

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#1372](https://github.com/yegor256/rultor/issues/1372), [#1373](https://github.com/yegor256/rultor/issues/1373), [#1377](https://github.com/yegor256/rultor/issues/1377) are still not solved.
